import { Layout } from "@/components/layout";

export default function Disclaimer() {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-12 md:py-20 max-w-3xl">
        <h1 className="text-4xl font-bold tracking-tight mb-8">Disclaimer</h1>
        
        <div className="prose dark:prose-invert max-w-none">
          <p className="text-muted-foreground mb-8">Last updated: January 2025</p>

          <p className="lead font-medium text-foreground">
            The information and tools provided by PH Calculators are for general informational and educational purposes only.
          </p>

          <h2>Not Professional Financial Advice</h2>
          <p>
            PH Calculators is not a financial advisor, accounting firm, law firm, or government agency. The calculations, results, and content on this website do not constitute professional financial, tax, or legal advice. You should not rely solely on the calculations provided by this website to make financial decisions, file tax returns, or dispute payroll records. Always consult with a certified public accountant (CPA), financial advisor, or legal professional regarding your specific situation.
          </p>

          <h2>No Guarantee of Accuracy</h2>
          <p>
            While we strive to keep our calculators updated with the latest regulations, circulars, and laws from the Bureau of Internal Revenue (BIR), Social Security System (SSS), PhilHealth, and Pag-IBIG, we make no representations, warranties, or guarantees—express or implied—regarding the absolute accuracy, reliability, completeness, or currentness of the results generated.
          </p>
          <p>
            Government rates, tax brackets, and contribution tables are subject to change without prior notice. Furthermore, actual payroll computations done by employers may differ slightly due to rounding rules, company-specific policies regarding taxable allowances, de minimis benefits, and integration of other deductions.
          </p>

          <h2>Use at Your Own Risk</h2>
          <p>
            Your use of the site and your reliance on any information generated by the calculators is solely at your own risk. Under no circumstance shall PH Calculators, its creators, or its affiliates have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site.
          </p>

          <h2>External Links</h2>
          <p>
            Our website may contain links to external websites that are not provided or maintained by or in any way affiliated with PH Calculators. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you notice any discrepancies in our calculations based on recent government circulars, we welcome your feedback. Please reach out to us via our <a href="/contact" className="text-primary hover:underline">Contact page</a> so we can review and update our algorithms accordingly.
          </p>
        </div>
      </div>
    </Layout>
  );
}
